version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "3000:80"
    stdin_open: true
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    stdin_open: true