name: ci

on:
  push:
    branches:
      - "main"

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: npm run bootstrap
      - name: build webapp
        run: npm run build:webapp
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile.webapp --tag salimondev/webapp:latest
      - name: Docker Push
        run: docker push salimondev/webapp:latest

    # steps:
    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v2
    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2
    #   - name: Login to DockerHub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_TOKEN }}
    #   - name: Build and push
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       file: ./Dockerfile.webapp
    #       push: true
    #       tags: salimondev/webapp:latest
    #       github-token: ${{ github.token }}
