name: ci

on:
  push:
    branches:
      - "main"

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: npm run bootstrap
      - name: build webapp
        run: npm run build:webapp
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile.webapp --tag salimondev/webapp:latest
      - name: Docker Push
        run: docker push salimondev/webapp:latest
      # deploy to aravan kubernates service
      - name: get deployment script
        run: wget -q https://napi.arvancloud.com/paas/v1/regions/ir-thr-mn1/downloads/cli/linux/arvan
      - name: make the script executable
        run: chmod +x arvan
      - name: login into kbs service
        run: echo "${{ secrets.ARVAN_TOKEN }}" | ./arvan login
      - name: deploy deployment
        run: ./arvan paas apply -f kubernates/webapp-deployment.yml
